# Generated by Django 2.2.7 on 2019-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoAppTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Başlık')),
                ('completed', models.BooleanField(verbose_name='Durum')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'sss',
            },
        ),
    ]
