# Generated by Django 2.2.7 on 2019-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapptheme',
            name='taskdurum',
            field=models.BooleanField(verbose_name='Task Durumu'),
        ),
    ]
