# Generated by Django 2.2.7 on 2019-12-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoapptheme',
            options={'verbose_name': '', 'verbose_name_plural': 'Todo List'},
        ),
    ]
