# Generated by Django 2.2.7 on 2019-12-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191217_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapptheme',
            old_name='text',
            new_name='title',
        ),
    ]
